---
# Ansible playbook for annotation tool deployment

- name: annotation tool
  hosts: localhost
  connection: local
  vars_prompt:
    - name: "admin_http_pass"
      prompt: "Enter password for admin user"

  vars:
    annotation_tool:
      installation_path: "/usr/local/annotations/"
      log_path: "/var/log/annotations/"
      user: "annotation"
      internal_port: "9001"
      base_dir_images: ""
    httpd:      
      VirtualHostPort: "80"

  roles:
    - role: installer
