---
# Ansible playbook for annotation tool deployment

- name: annotation tool
  hosts: localhost
  ##connection: local
  vars_prompt:
    - name: "admin_http_pass"
      prompt: "Enter password for admin user"

  vars:
    annotation_tool:
      installation_path: "/usr/local/annotations/"
      log_path: "/var/log/annotations/"
      user: "annotation"
      internal_port: "9011"
      base_dir_images: "/mnt/fs_servicios/cognitiv/data/tmp/img"
      base_dir_ann: "/mnt/fs_servicios/cognitiv/data/tmp/ann"
    httpd:
      VirtualHostPort: "8000"

  roles:
    - role: installer
